name: build

on: [push, pull_request]

jobs:
  build:
    uses: monamaret/agora-meta/.github/workflows/build.yml@main

  snapshot:
    uses: monamaret/agora-meta/.github/workflows/snapshot.yml@main
    secrets:
      goreleaser_key: ${{ secrets.GORELEASER_KEY }}